### ISSUE TITLE
Switch to BSD license and exchange linedit for readline

### ISSUE THREAD

**Issue by Symbolics** [fukamachi/mondo#1]
Using [linedit ](https://thrysoee.dk/editline/) and dropping the GPL license would mean this could be used in a lot more places. `libedit` is supposed to be 100% compatible with GNU readline.

**Comment by fukamachi** [comment]
At the moment, my goal is to finish the project quickly with a more mature and accessible library, rather than to get people who don't use this because of the license.

I'll consider when I have time in the future and the license becomes an issue.
