### ISSUE TITLE
trouble starting swank server

### ISSUE THREAD

**Issue by indraniel** [fukamachi/mondo#3]
I recently started using roswell after reading your nice series at https://fukamachi.hashnode.dev/ .  I was also trying to use mondo along with it.  I did the following:

```
$ ros install fukamachi/mondo
$ mondo --server vlime
[15:27:51] <ERROR> Failed to start a swank server: Incorrect I/O specifier T for :ERROR-OUTPUT
```

Is there something that I've done amiss?

**Comment by fukamachi** [comment]
Thank you for reporting!

It seems like it is a bug recently added. As it may be fixed at the latest commit, please retry it after `ros update mondo`.
If not fixed yet, paste the output of `ros config` on your environment.

**Comment by indraniel** [comment]
Thank you!  This seems to work much better now:

```
$ mondo --server vlime
Server created: (#(127 0 0 1) 50993)
SBCL 2.2.1 running at 127.0.0.1:50005 (pid=27731)
CL-USER>
```

I have a couple extra questions:

1.  Is it possible to specify which port the swank server is run?
2. From mondo's help _(via `mondo --help`)_ I see the following:
    ```
        --server [TYPE]
        Start a server to communicate with external tools such as editors
    ```
    Aside from the TYPE parameter `vlime`, are there any others?  Can I use the `vlime` type on vim/neovim's [`slimv`](https://github.com/kovisoft/slimv) plugin as well?

**Comment by fukamachi** [comment]
> Is it possible to specify which port the swank server is run?

Unfortunately, there's no such option yet.
At the starting point, I had considered "mondo" as a Swank client, but I heard people who think of it as a Swank server starter. Perhaps it'd be better to add.

> Aside from the TYPE parameter vlime, are there any others? Can I use the vlime type on vim/neovim's [slimv](https://github.com/kovisoft/slimv) plugin as well?

Nothing yet, too. I have a plan to add LSP support in the future.
