### ISSUE TITLE
Default repl for roswell run

### ISSUE THREAD

**Issue by jgarte** [fukamachi/mondo#5]
Hi,

Is it possible to set roswell as the default repl for roswell's `ros run` command?

**Comment by fukamachi** [comment]
Do you mean, the way to launch mondo when running `ros run`?

Nope. You can't (and shouldn't) override Roswell commands.
It's possible to add a new subcommand like `ros repl` or `ros mondo`, though.

**Comment by jgarte** [comment]
> Do you mean, the way to launch mondo when running `ros run`?

Yes, that is what I meant.
 
> Nope. You can't (and shouldn't) override Roswell commands. It's possible to add a new subcommand like `ros repl` or `ros mondo`, though.

Would I be writing that subcommand in C [like this one](https://github.com/roswell/roswell/blob/master/src/cmd-install.c)?

I'm very new to roswell.

**Comment by fukamachi** [comment]
Don't worry, most people don't know about Roswell well. 😆 

You don't need to write in C to add a new subcommand.
Roswell takes `ros-xxx.ros` script as a subcommand, and allows to run with `ros xxx`.
[cl-repl](https://github.com/koji-kojiro/cl-repl) is an actual example of using this feature.

So, I'd like to make sure if adding `ros-repl.ros` or `ros-mondo.ros` meets your request.

**Comment by jgarte** [comment]
> 

Yes, that meets my request. Thank you! I'll close this issue and give that a try.
